test:
	python3 posTagging.py -d 0 input/macmorpho-v3/macmorpho-train.txt input/macmorpho-v3/macmorpho-dev.txt input/macmorpho-v3/macmorpho-test.txt

pre_test:
	python3 posTagging.py -d 1 input/macmorpho-v3/macmorpho-train.txt input/macmorpho-v3/macmorpho-dev.txt input/macmorpho-v3/macmorpho-test.txt
